curso.mvc.web/Models/Curso/ListarCursoViewModelOutput.cs
namespace curso.mvc.web.Models
{
    public class ListarCursoViewModelOutput
    {
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Login { get; set; }
    }
}

curso.mvc.web/Models/Curso/RegistrarCursoViewModelInput.cs
using System.ComponentModel.DataAnnotations;

namespace curso.mvc.web.Models
{
    public class RegistrarCursoViewModelInput
    {
        [Required(ErrorMessage = "O nome é obrigatório")]
        public string Nome { get; set; }


        [Required(ErrorMessage = "A descrição é obrigatória")]
        public string Descricao { get; set; }
    }
}

curso.mvc.web/Models/Curso/RegistrarCursoViewModelOutput.cs
namespace curso.mvc.web.Models
{
    public class RegistrarCursoViewModelOutput
    {
        public string Nome { get; set; }

        public string Descricao { get; set; }
    }
}

curso.mvc.web/Models/ErrorViewModel.cs
namespace curso.mvc.web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

curso.mvc.web/Models/Usuario/LoginViewModelInput.cs
namespace curso.mvc.web.Models
{
    public class LoginViewModelInput
    {
        public string Login { get; set; }
        public string Senha { get; set; }
    }
}

curso.mvc.web/Models/Usuario/LoginViewModelOutput.cs
namespace curso.mvc.web.Models.Usuario
{
    public class LoginViewModelOutput
    {
        public string Token { get; set; }
        public LoginViewModelDetalhesOutput Usuario { get; set; }
    }
    public class LoginViewModelDetalhesOutput
    {
        public int Codigo { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
    }
}

curso.mvc.web/Models/Usuario/RegistrarUsuarioViewModelInput.cs
using System.ComponentModel.DataAnnotations;

namespace curso.mvc.web.Models
{
    public class RegistrarUsuarioViewModelInput
    {
        [Required(ErrorMessage = "O login é obrigatório")]
        public string Login { get; set; }

        [Required(ErrorMessage = "O email é obrigatório")]
        [EmailAddress(ErrorMessage = "O email é inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "a senha é obrigatória")]
        public string Senha { get; set; }
    }
}

curso.mvc.web/Controllers/CursoController.cs
using curso.mvc.web.Models;
using curso.mvc.web.Services;
using Microsoft.AspNetCore.Mvc;
using Refit;
using System;
using System.Threading.Tasks;

namespace curso.mvc.web.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    public class CursoController : Controller
    {
        private readonly ICursoService _service;
        public CursoController(ICursoService service)
        {
            _service = service;
        }
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CadastrarAsync(RegistrarCursoViewModelInput input)
        {
            try
            {
                var retorno = await _service.Registrar(input);

                ModelState.AddModelError("", $"Cadastro realizado com sucesso. Curso: {retorno.Nome}");
            }
            catch (ApiException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Listar()
        {
            try
            {
                var retorno = await _service.Listar();
                return View(retorno);
            }
            catch (ApiException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(new ListarCursoViewModelOutput());
        }

    }
}

curso.mvc.web/Controllers/HomeController.cs
using curso.mvc.web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace curso.mvc.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

curso.mvc.web/Controllers/UsuarioController.cs
using curso.mvc.web.Models;
using curso.mvc.web.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Refit;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace curso.mvc.web.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _service;
        public UsuarioController(IUsuarioService service)
        {
            _service = service;
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(RegistrarUsuarioViewModelInput input)
        {
            try
            {
                var retorno = await _service.Registrar(input);

                ModelState.AddModelError("", $"Cadastro realizado com sucesso para: {retorno.Login}");
            }
            catch (ApiException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }

        public IActionResult Logar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogarAsync(LoginViewModelInput input)
        {
            try
            {
                var retorno = await _service.Logar(input);

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, retorno.Usuario.Codigo.ToString()),
                    new Claim(ClaimTypes.Name, retorno.Usuario.Login),
                    new Claim(ClaimTypes.Email, retorno.Usuario.Email),
                    new Claim("token", retorno.Token),

                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    ExpiresUtc = new DateTimeOffset(DateTime.Now.AddDays(1))
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                ModelState.AddModelError("", $"Usuário autenticado com sucesso. Token: {retorno.Token}");
            }
            catch (ApiException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }

        public IActionResult Logout()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Logout2()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction($"{nameof(Logar)}");
        }
    }
}

curso.mvc.web/Views/Curso/Cadastrar.cshtml
@model curso.mvc.web.Models.RegistrarCursoViewModelInput

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar</h1>

<h4>RegistrarCursoViewModelInput</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cadastrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

curso.mvc.web/Views/Curso/Listar.cshtml
@model IEnumerable<curso.mvc.web.Models.ListarCursoViewModelOutput>

@{
    ViewData["Title"] = "Listar";
}

<h1>Listar</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Login)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

curso.mvc.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

curso.mvc.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - curso.mvc.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">curso.mvc.web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Cadastrar">Novo Usuário</a>
                        </li>
                         @if (User.Identity.IsAuthenticated) {
                               <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  @User.Identity.Name
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" asp-controller="Curso" asp-action="Cadastrar">Novo Curso</a>
                                  <a class="dropdown-item" asp-controller="Curso" asp-action="Listar">Listar Cursos</a>
                                <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" asp-controller="Usuario" asp-action="Logout">Sair</a>
                                </div>
                              </li>
                         } 
                         else
                         {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logar">Logar</a>
                            </li>
                         }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - curso.mvc.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

curso.mvc.web/Views/Usuario/Cadastrar.cshtml
@model curso.mvc.web.Models.RegistrarUsuarioViewModelInput

@{
    ViewData["Title"] = "Registrar";
}

<h1>Registrar</h1>

<h4>RegistrarUsuarioViewModelInput</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cadastrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

curso.mvc.web/Views/Usuario/Logar.cshtml
@model curso.mvc.web.Models.LoginViewModelInput

@{
    ViewData["Title"] = "Logar";
}

<h1>Logar</h1>

<h4>LoginViewModelInput</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Logar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

curso.mvc.web/Views/Usuario/Logout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <form asp-contoller="Usuario" asp-action="Logout2">
	<div class="card" style="width: 18rem;">
		<div class="card-body">
			<h5 class="card-title">Sair</h5>
			<p class="card-text">Deseja mesmo sair?</p>
			<input type="submit" value="Sim" class="btn btn-primary" />
		</div>
	</div>
</form>
}